# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_status\
$git_branch\
$cmd_duration\
$line_break\
$python\
$rust\
$character"""

right_format = "$time"

# Inserts a blank line between shell prompts
add_newline = true

[cmd_duration]
format = '[$duration]($style)'

[directory]
read_only = " "
truncate_to_repo = false
style = "blue"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[git_branch]
format = "[$branch]($style)"

[git_status]
format = "[[($all_status)](218) ($ahead_behind$stashed)]($style)"

[python]
symbol = ""
format = "[($symbol $virtualenv)]($style)"

[rust]
symbol = ""
format = "[($symbol $version)]($style)"

[time]
disabled = false
format = "[$time]($style)"
