# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$cmd_duration | $time"

# Inserts a blank line between shell prompts
add_newline = true

[cmd_duration]
format = '\([⏱ $duration]($style)\)'

[deno]
format = '\([$symbol($version)]($style)\)'

[directory]
read_only = " "
truncate_to_repo = false

[docker_context]
symbol = " "
format = '\([$symbol$context]($style)\)'

[git_branch]
symbol = " "
format = '[$symbol$branch]($style)'

[git_status]
format = '([\($all_status$ahead_behind\)]($style))'

[memory_usage]
symbol = " "
format = '\($symbol[$ram( | $swap)]($style)\)'

[nodejs]
symbol = " "
format = '\([$symbol($version)]($style)\)'

[package]
symbol = " "
format = '\([$symbol$version]($style)\)'

[python]
symbol = " "
format = '\([${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\)'

[rust]
symbol = " "
format = '\([$symbol($version)]($style)\)'

[sudo]
format = '\([as $symbol]\)'


[time]
disabled = false
format = '\([$time]($style)\)'

