#!/bin/bash

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 3
berryc title_height       0
berryc top_gap            20

# Set decoration colors
berryc inner_focus_color   B26089
berryc inner_unfocus_color 496886

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"

# Autostart
bash "$HOME"/.config/berry/bin/autostart.sh
