#!/bin/bash

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 3
berryc title_height       0
berryc top_gap            30

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   B26089
berryc inner_unfocus_color 496886
berryc text_focus_color    FFFFFF
berryc text_unfocus_color  011826

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Inter-9"

# Autostart
bash "$HOME"/.config/berry/bin/autostart.sh
