theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline  = true
color-modes = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.whitespace.render]
space   = "all"
tab     = "all"
newline = "all"

[editor.whitespace.characters]
space   = "·"
nbsp    = "⍽"
tab     = "→"
newline = "⏎"
